config/routes.rb
Acm::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :shirt_sizes

  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user

  resources :positions

  resources :users, only: [:index]

  resources :members

  root to: 'members#new'

end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :title
  has_many :members
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= simple_form_for(@position, html: { class: 'form-horizonal' }) do |f| %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<% if user_signed_in? %>

  <h2>Editing position</h2>

  <%= render 'form' %>

  <%= link_to 'Show', @position %> |
  <%= link_to 'Back', positions_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>

app/views/positions/index.html.erb
<% if user_signed_in? %>

  <h2>Positions</h2>

  <table class="table table-striped table-bordered">
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @positions.each do |position| %>
      <tr>
        <td><%= position.title %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <br />

  <%= link_to 'New Position', new_position_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>

app/views/positions/new.html.erb
<% if user_signed_in? %>

  <h2>New position</h2>

  <%= render 'form' %>

  <%= link_to 'Back', positions_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>

app/views/positions/show.html.erb
<% if user_signed_in? %>

  <p id="notice"><%= notice %></p>

  <p>
    <b>Title:</b>
    <%= @position.title %>
  </p>


  <%= link_to 'Edit', edit_position_path(@position) %> |
  <%= link_to 'Back', positions_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>