config/routes.rb
Acm::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :shirt_sizes

  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user

  resources :positions

  resources :users, only: [:index]

  resources :members

  root to: 'members#new'

end

app/controllers/shirt_sizes_controller.rb
class ShirtSizesController < ApplicationController
  # GET /shirt_sizes
  # GET /shirt_sizes.json
  def index
    @shirt_sizes = ShirtSize.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shirt_sizes }
    end
  end

  # GET /shirt_sizes/1
  # GET /shirt_sizes/1.json
  def show
    @shirt_size = ShirtSize.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shirt_size }
    end
  end

  # GET /shirt_sizes/new
  # GET /shirt_sizes/new.json
  def new
    @shirt_size = ShirtSize.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shirt_size }
    end
  end

  # GET /shirt_sizes/1/edit
  def edit
    @shirt_size = ShirtSize.find(params[:id])
  end

  # POST /shirt_sizes
  # POST /shirt_sizes.json
  def create
    @shirt_size = ShirtSize.new(params[:shirt_size])

    respond_to do |format|
      if @shirt_size.save
        format.html { redirect_to @shirt_size, notice: 'Shirt size was successfully created.' }
        format.json { render json: @shirt_size, status: :created, location: @shirt_size }
      else
        format.html { render action: "new" }
        format.json { render json: @shirt_size.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shirt_sizes/1
  # PUT /shirt_sizes/1.json
  def update
    @shirt_size = ShirtSize.find(params[:id])

    respond_to do |format|
      if @shirt_size.update_attributes(params[:shirt_size])
        format.html { redirect_to @shirt_size, notice: 'Shirt size was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shirt_size.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shirt_sizes/1
  # DELETE /shirt_sizes/1.json
  def destroy
    @shirt_size = ShirtSize.find(params[:id])
    @shirt_size.destroy

    respond_to do |format|
      format.html { redirect_to shirt_sizes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shirt_sizes_helper.rb
module ShirtSizesHelper
end

app/views/shirt_sizes/_form.html.erb
<%= simple_form_for(@shirt_size) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :size %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shirt_sizes/edit.html.erb
<% if user_signed_in? %>
  <h2>Editing shirt_size</h2>

  <%= render 'form' %>

  <%= link_to 'Show', @shirt_size %> |
  <%= link_to 'Back', shirt_sizes_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>

app/views/shirt_sizes/index.html.erb
<% if user_signed_in? %>

  <h2>Shirt Sizes</h2>

  <table class="table table-striped table-bordered">

    <tr>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @shirt_sizes.each do |shirt_size| %>
      <tr>
        <td><%= shirt_size.size %></td>
        <td><%= link_to 'Show', shirt_size %></td>
        <td><%= link_to 'Edit', edit_shirt_size_path(shirt_size) %></td>
        <td><%= link_to 'Destroy', shirt_size, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <br />

  <%= link_to 'New Shirt size', new_shirt_size_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>

app/views/shirt_sizes/new.html.erb
<% if user_signed_in? %>

  <h2>New shirt_size</h2>

  <%= render 'form' %>

  <%= link_to 'Back', shirt_sizes_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>

app/views/shirt_sizes/show.html.erb
<% if user_signed_in? %>

  <p id="notice"><%= notice %></p>

  <p>
    <b>Size:</b>
    <%= @shirt_size.size %>
  </p>

  <%= link_to 'Edit', edit_shirt_size_path(@shirt_size) %> |
  <%= link_to 'Back', shirt_sizes_path %>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>