config/routes.rb
Acm::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :shirt_sizes

  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user

  resources :positions

  resources :users, only: [:index]

  resources :members

  root to: 'members#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
      redirect_to root_url, notice: "User deleted."
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if user_signed_in? %>

  <h2>ACM Registrar Users</h2>

  <table class="table table-bordered table-striped">

    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <% if current_user != user %>
            <%= link_to 'Destroy', destroy_user_path(user), method: :delete, data: { confirm: "You sure?" }  %>
          <% end %>
        </td>
      </tr>
    <% end %>

  </table>

<% else %>

  <p>Please <%= link_to 'Sign In', new_user_session_path %>!</p>

<% end %>